    var btn1 = document.createElement("button");
        btn1.innerHTML = "GROEN";
        btn1.setAttribute("onclick", "document.body.style.backgroundColor = ('green')");
        document.getElementById("container").appendChild(btn1);
        btn1.style.backgroundColor = "green";
        btn1.style.width = "200px";
        btn1.style.height = "50px";
        btn1.style.border = "none";
        btn1.style.color = "white";
        btn1.style.marginLeft = "75px";
        btn1.style.marginTop = "50px";
    var btn2 = document.createElement("button");
        btn2.innerHTML = "ROOD";
        btn2.setAttribute("onclick", "document.body.style.backgroundColor = ('red')");
        document.getElementById("container").appendChild(btn2);
        btn2.style.backgroundColor = "red";
        btn2.style.width = "200px";
        btn2.style.height = "50px";
        btn2.style.border = "none";
        btn2.style.color = "white";
        btn2.style.marginLeft = "25px";
        btn2.style.marginTop = "50px";
    var btn3 = document.createElement("button");
        btn3.innerHTML = "BLAUW";
        btn3.setAttribute("onclick", "document.body.style.backgroundColor = ('blue')");
        document.getElementById("container").appendChild(btn3);
        btn3.style.backgroundColor = "blue";
        btn3.style.width = "200px";
        btn3.style.height = "50px";
        btn3.style.border = "none";
        btn3.style.color = "white";
        btn3.style.marginLeft = "25px";
        btn3.style.marginTop = "50px";